#!/bin/zsh

autoload colors ; colors

GIT=`which git`
MAIN_PATH="/srv/httpd"
PROJECTS=(
    elasticsearch-php-bundle

    unity-backend-core
    unity-backend-ictcareer
    unity-backend-jobs
    unity-backend-jsm

    unity-frontend-common
    unity-frontend-ictcareer
    unity-frontend-jobs
    unity-frontend-jsm
)

for PROJECT in $PROJECTS; do
    workdir="$MAIN_PATH/$PROJECT"
    gitdir="$MAIN_PATH/$PROJECT/.git"

    echo "$fg[yellow]$PROJECT's$reset_color branches:"
    $GIT --git-dir=$gitdir --work-tree=$workdir branch
    echo
done
