#!/bin/zsh

autoload colors ; colors

GIT=`which git`
folders=(/srv/modules /srv/httpd)

# find git folders in project directories
for folder in $folders; do
  for dir in $(find "$folder" -maxdepth 3 -mindepth 2 -type d -name .git); do
      git_dirs+=(${dir/\/.git/})
  done
done

for gitdir in $git_dirs; do
    echo "$fg[yellow]$gitdir$reset_color is on:"
    branch=`$GIT --git-dir="$gitdir/.git" --work-tree=$gitdir rev-parse --abbrev-ref HEAD`
    ref=`$GIT --git-dir="$gitdir/.git" --work-tree=$gitdir rev-parse HEAD`
    echo "  $branch ($ref)"
done
